language: go

go:
- 1.13

addons:
  apt:
    packages:
    - rpm

env:
- GO111MODULE=on

script:
- go generate ./...
- go build
- ./gossiped
- go test ./... -v -cover -coverprofile=coverage.txt --bench=. -benchmem

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
