username: Alexander N. Skovpen
address: 2:5020/9696.128
areafile:
  path: /etc/ftn/hpt/config
  type: fidoconfig # fidoconfig, areas.bbs, squish
log: ./app.log
template: goated.tpl
origin: Just Origin
chrs: CP866 2 # <charset> <lvl> http://ftsc.org/docs/fts-5003.001
areas:
  - name: utf-8
    chrs: UTF-8 4
